---
- name: Copy remoteweb files
  copy:
    src: "../../../../python/{{ item }}"
    dest: "{{ remoteweb_dir }}"
    mode: '0700'
  loop:
    - remoteweb.py
    - requirements.txt
    - templates

- name: Install requirements
  pip:
    chdir: "{{ remoteweb_dir }}"
    requirements: "requirements.txt"
    executable: pip3

- name: Install init file for remoteweb
  copy:
    src: "remoteweb.service"
    dest: "/etc/systemd/system/"
    owner: root
    group: root
    mode: '0644'

- name: Start remoteweb
  systemd:
    name: remoteweb
    state: started
    enabled: yes
