---
- name: Create LIRC directory
  file:
    path: "/etc/lirc"
    state: directory
    owner: root
    group: root

- name: Copy LIRCD configuration file
  copy:
    src: "lirc_options.conf"
    dest: "/etc/lirc/lirc_options.conf"
    owner: root
    group: root
    mode: '0644'

- name: Install LIRC apt package
  apt:
    name: lirc
    state: present

- name: Copy LIRCD remote configurations
  copy:
    src: "{{ item }}"
    dest: "/etc/lirc/lircd.conf.d/"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - "LG-AKB73975761.conf"
    - "Pioneer-XXD3067.conf"
    - "CLAS_LED.conf"

- name: Install init file for separate LIRC instance for IR reception
  copy:
    src: "lircd-rx.service"
    dest: "/etc/systemd/system/"
    owner: root
    group: root
    mode: '0644'

- name: Start separate LIRC instance for IR reception
  systemd:
    name: lircd-rx
    state: started
    enabled: yes
