---
- name: Create directory for ePaper display app
  file:
    path: "{{ epaper_display_dir }}/lib/waveshare_epd"
    state: directory
    owner: pi
    group: pi

- name: Get ePaper display python library
  get_url:
    url: "{{ item }}"
    dest: "{{ epaper_display_dir }}/lib/waveshare_epd"
    mode: '0744'
  loop:
    - "https://raw.githubusercontent.com/waveshare/e-Paper/master/RaspberryPi_JetsonNano/python/lib/waveshare_epd/epd2in7.py"
    - "https://github.com/waveshare/e-Paper/blob/262640ae5ab36ac01ee712422e1471330adb4cc7/RaspberryPi%26JetsonNano/python/lib/waveshare_epd/epdconfig.py"
# Using a patched version of epdconfig.py under python/lib
# The fix is in a PR: https://github.com/waveshare/e-Paper/pull/71, so it may appear to the master someday
#    - "https://raw.githubusercontent.com/waveshare/e-Paper/master/RaspberryPi%26JetsonNano/python/lib/waveshare_epd/epdconfig.py"

- name: Copy ePaper display files
  copy:
    src: "../../../../python/{{ item }}"
    dest: "{{ epaper_display_dir }}"
    mode: '0755'
  loop:
    - epaper_display.py
    - lib

- name: Install init file for ePaper display
  copy:
    src: "epaper-display.service"
    dest: "/etc/systemd/system/"
    owner: root
    group: root
    mode: '0644'

- name: Start ePaper display
  systemd:
    name: epaper-display
    state: started
    enabled: yes
