---
- name: Install deepspeech
  pip:
    name: deepspeech
    state: present
    executable: pip3

- name: Create directory for deepspeech
  file:
    path: "{{ deepspeech_dir }}"
    state: directory
    owner: pi
    group: pi

- name: Get deepspeech data
  get_url:
    url: "{{ item }}"
    dest: "{{ deepspeech_dir }}"
    mode: "0644"
  loop:
    - "https://github.com/mozilla/DeepSpeech/releases/download/v0.7.1/deepspeech-0.7.1-models.tflite"
    - "https://github.com/mozilla/DeepSpeech/releases/download/v0.7.1/deepspeech-0.7.1-models.scorer"


